# Generated by Django 3.0.7 on 2020-06-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200615_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='movie_picks',
        ),
    ]
